### ISSUE TITLE
安装失败 

### ISSUE THREAD

**Issue by 63898900** [david7207/oneindexMod#10]
Fatal error: Uncaught Error: Call to a member function exists() on boolean in /home/ftp/p/p63898900/wwwroot/lib/RedisDrive.php:67 Stack trace: #0 /home/ftp/p/p63898900/wwwroot/init.php(81): RedisDrive->exists() #1 /home/ftp/p/p63898900/wwwroot/index.php(13): cache('refresh_token') #2 {main} thrown in /home/ftp/p/p63898900/wwwroot/lib/RedisDrive.php on line 67

**Comment by bingbaga** [comment]
这个是你php的redis驱动没装吧？你服务器信息发给我下，安装了什么驱动类似的，或者php的redis驱动什么版本的
