### ISSUE TITLE
上传图片提示请求上传接口出现异常

### ISSUE THREAD

**Issue by ghost** [david7207/oneindexMod#15]
上传图片提示请求上传接口出现异常 2019/5/10

**Comment by ghost** [comment]
怎么解决

**Comment by bingbaga** [comment]
总有很多错误嘛，我那个站都没管他，一直可以的，今晚我来看下，

**Comment by ghost** [comment]
好的，多谢啦！比原版好用，希望把回调地址改一下，最新的是https://oneindex.github.io/，还有图床问题，谢谢大佬！

**Comment by bingbaga** [comment]
好的，回调地址改下，我是手动写进去的，怪不得我没问题，晚上有空上个版本
