### ISSUE TITLE
您好。图片上传完跳转到图片地址及404

### ISSUE THREAD

**Issue by amoshere** [david7207/oneindexMod#2]
而不是留在图床页面显示图片链接和markdown引用地址，怎么解决？是不是我哪里弄错了

**Comment by bingbaga** [comment]
你po张图呀

**Comment by amoshere** [comment]
好了，rewrite里我删了两段代码

**Comment by amoshere** [comment]
说一下，我看这个，跟着删了两段代码好了。谢谢了
https://github.com/donwa/oneindex/issues/14
