### ISSUE TITLE
无法访问此网站 找不到 ju.tn 的服务器 IP 地址

### ISSUE THREAD

**Issue by MahoushoujoMadoka** [david7207/oneindexMod#20]
大佬你的中转网站无法访问绑定不了

**Comment by sagrada98** [comment]
请将网址修改为https://oneindex.github.io/    或者直接从我的分支拉取

**Comment by MahoushoujoMadoka** [comment]
我有尝试过修改成你说的这个链接，但是没有效果，貌似后台代码固定成这个链接了

**Comment by sagrada98** [comment]
我指的是修改源代码里面哦，并不是在安装页面修改

**Comment by MahoushoujoMadoka** [comment]
我昨天有试过改代码, 奈何不懂php所以没改成功, 后面我发现有一个方法, 好就是绑定完了微软账号之后提示ju.tn无法访问的时候, 可以把地址栏上面的ju.tn换成https://oneindex.github.io/ 然后在回车,就提示绑定成功了

**Comment by MahoushoujoMadoka** [comment]
感谢大佬解答 @luojiaquan7737

**Comment by sagrada98** [comment]
抱歉，还以为你懂PHP 既然你解决了，那么我补充一下，方便之后的人解决！
跳转网址修改在目录“controller”下的“AdminController.php”  将里面的https://ju.tn替换为https://oneindex.github.io/

**Comment by bingbaga** [comment]
起始不需要，程序自带跳转了，除非你不是用的https，但是不建议你这么做

**Comment by sagrada98** [comment]
程序自带的域名已经是不能用了，我记得项目原作者有说过 @david7207

**Comment by bingbaga** [comment]
不是，我的意思是你自己的域名，会自动获取的，不需要第三方的来，等会我看看，如果不是的话今天提交个版本上去

**Comment by sagrada98** [comment]
之前我好像试过了不行（套了一层CDN），不晓得单独的https能不能过

**Comment by bingbaga** [comment]
可以了，先改成那个https://oneindex.github.io/
