### ISSUE TITLE
nginx添加伪静态后仍然无法去除/?/访问

### ISSUE THREAD

**Issue by OHMCFXG** [david7207/oneindexMod#21]
nginx添加伪静态规则，并在后台打开“去掉/?/”后，访问二级目录仍然404。
原版oneindex正常。

我试了一下您的站点是正常的，是不是修改了什么东西忘记同步到github了呢？

伪静态规则如下：
`if (!-f $request_filename){
    set $rule_0 1$rule_0;
}
if (!-d $request_filename){
    set $rule_0 2$rule_0;
}
if ($rule_0 = "21"){
    rewrite ^(/.*)$ /?/$1 last;
}`

**Comment by bingbaga** [comment]
这啥规则？
