### ISSUE TITLE
提交bug和建议。

### ISSUE THREAD

**Issue by 1gcat** [david7207/oneindexMod#5]
# bug  

- md文件显示为空。
- 视频文件可正常播放但无下载地址显示。（测试格式为mp4）

# 建议    

em..其实就是不要脸得来催更，啊哈哈哈。希望增加一下防盗链的功能，可以参考原版OneIndex的防盗链代码，但建议不要直接拿master里的代码作修改，bug太多。

# 啰嗦  

非常感谢作者对OneIndex的魔改，这几天正愁不知道如何使用redis缓存系统，使用您的mod就解决了。之前一直在用原版OneIndex，但是新代码bug太多了，层出不穷，之后试过同类产品PyOne和OLAIndex，特别是OLAIndex非常棒，但奈何其页面加载速度奇慢，兜兜转转又用回OneIndex了，现在用着您的mod，总算舒服了。

**Comment by bingbaga** [comment]
好，这几天我整理下bug，这几天和即将来的假期来调整一波，谢谢关注和反馈哈

**Comment by bingbaga** [comment]
问题已修复，请全新安装
