### ISSUE TITLE
大佬，求帮忙看个报错

### ISSUE THREAD

**Issue by 1shanyue1** [david7207/oneindexMod#7]
这是z怎么回事呢
![_20190115174343](https://user-images.githubusercontent.com/23732055/51172100-745bcd80-18ed-11e9-89c7-623e93ee3f8f.png)

**Comment by yeshan333** [comment]
> 这是z怎么回事呢
> ![_20190115174343](https://user-images.githubusercontent.com/23732055/51172100-745bcd80-18ed-11e9-89c7-623e93ee3f8f.png)

你要安装一下redis扩展
